name: flutter_starter_kit
description: Flutter Starter Kit with Bloc pattern and Rxdart
authors:
 - King Wu <king.wuff101@gmail.com>
homepage: https://github.com/KingWu/flutter_starter_kit
maintainer: King Wu (@kw101)

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.3.0

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fluro: 1.6.3
  dio: 3.0.9
  logging: 0.11.4
  json_annotation: 3.0.1
  sprintf: 4.0.2
  rxdart: 0.22.6
  cached_network_image: 2.0.0
  sqflite: 1.3.0+2
  smooth_star_rating: 1.1.1
#  flutter_stetho: 0.5.2
  analyzer: 0.39.10

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: 0.1.3
  flutter_platform_widgets: 0.50.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.10.0
  json_serializable: 3.3.0
  gen_lang: 0.1.3
  lang_table: 0.2.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font isSupported
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
